[package]
cairo-version = "2.15.0"
name = "planets"
version = "0.1.0"
edition = "2024_07"

[cairo]
sierra-replace-ids = true

[tool.scarb]
allow-prebuilt-plugins = ["dojo_cairo_macros", "snforge_std"]

[dependencies]
starknet = "2.15.0"
dojo = "1.8.0"
game_components_embeddable_game_standard = { git = "https://github.com/Provable-Games/game-components.git", tag = "v1.1.0" }
game_components_interfaces = { git = "https://github.com/Provable-Games/game-components.git", tag = "v1.1.0" }

openzeppelin_access = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_introspection = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_token = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_interfaces = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }
openzeppelin_upgrades = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v3.0.0" }

alexandria_encoding = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "v0.9.0" }
graffiti = { git = "https://github.com/Provable-Games/graffiti"}

[scripts]
migrate = "sozo migrate -P sepolia --rpc-url https://api.cartridge.gg/x/starknet/sepolia/rpc/v0_9 --rpc-header \"Authorization: Bearer $CARTRIDGE_RPC\" --manifest-abi-format per_contract"

[dev-dependencies]
cairo_test = "2.13.1"
dojo_snf_test = "1.8.0"
snforge_std = "0.51.2"

[[target.starknet-contract]]
build-external-contracts = ["dojo::world::world_contract::world"]


[profile.sepolia]

[migration]
manifest_abi_format = "per_contract"